(lecture03:pandas)=

Christopher Draper

# The Python Data Analysis Library

[Pandas](https://pandas.pydata.org/) is Python library that provides fast, flexible and data structures that lets you work real life data quickly.
Typically, we import the library like this:

In [2]:
import pandas as pd

Let's load the `catalysis.csv` file we created before. I will download it for you first:

In [3]:
!curl -O https://raw.githubusercontent.com/PurdueMechanicalEngineering/me-239-intro-to-data-science/master/data/catalysis.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   258  100   258    0     0   1230      0 --:--:-- --:--:-- --:--:--  1234

The file should now be in the working directory. Let's check that:

In [4]:
!ls catalysis.csv

catalysis.csv

We can now load the file into a pandas [DataFrame](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html):

In [70]:
data = pd.read_csv('catalysis.csv')
data

   Time     NO3     NO2      N2    NH3    N2O
0     0  500.00    0.00    0.00   0.00   0.00
1    30  250.95  107.32   18.51   3.33   4.98
2    60  123.66  132.33   74.85   7.34  20.14
3    90   84.47   98.81  166.19  13.14  42.10
4   120   30.24   38.74  249.78  19.54  55.98
5   150   27.94   10.42  292.32  24.07  60.65
6   180   13.54    6.11  309.50  27.26  62.54

DataFrame is a two-dimensional data structure that can store data of different types (e.g., numbers, strings, booleans) in a table format. It is similar to a spreadsheet. The columns can have names. Here are the column names:

In [97]:
data.columns

Index(['Time', 'NO3', 'NO2', 'N2', 'NH3', 'N2O', 'X'], dtype='object')

Let's summarize the data. The function `DataFrame.describe()` provides a summary of the data. It shows the mean, standard deviation, minimum, maximum, and quartiles of the data:

In [72]:
data.describe()

             Time         NO3         NO2          N2        NH3        N2O
count    7.000000    7.000000    7.000000    7.000000   7.000000   7.000000
mean    90.000000  147.257143   56.247143  158.735714  13.525714  35.198571
std     64.807407  175.825979   55.215843  129.625326  10.498362  26.626079
min      0.000000   13.540000    0.000000    0.000000   0.000000   0.000000
25%     45.000000   29.090000    8.265000   46.680000   5.335000  12.560000
50%     90.000000   84.470000   38.740000  166.190000  13.140000  42.100000
75%    135.000000  187.305000  103.065000  271.050000  21.805000  58.315000
max    180.000000  500.000000  132.330000  309.500000  27.260000  62.540000

How can we extract the data pertaining to "NO3"? Easy!

In [46]:
data['NO3']

0    500.00
1    250.95
2    123.66
3     84.47
4     30.24
5     27.94
6     13.54
Name: NO3, dtype: float64

What type of object is this? Let's check:

In [68]:
type(data['NO3'])

pandas.core.series.Series

Aha! It's a pandas [Series](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html)! You can go to the documentation to see what you can do with it.

What if you want to extract the data pertaining to "NO3" and "NO2"? You can do this by passing a list of column names to the dataframe:

In [48]:
data[['NO3', 'NO2']]

      NO3     NO2
0  500.00    0.00
1  250.95  107.32
2  123.66  132.33
3   84.47   98.81
4   30.24   38.74
5   27.94   10.42
6   13.54    6.11

What if I ask for a column that does not exist? Try it out to see the error.

Another useful operation is to extract a subset of the dataframe based on some condition. For example, let's extract the data for the first 90 minutes:

In [73]:
data['doesntexist']

KeyError: 'doesntexist'

In [74]:
data[data['Time'] <= 90]

   Time     NO3     NO2      N2    NH3    N2O
0     0  500.00    0.00    0.00   0.00   0.00
1    30  250.95  107.32   18.51   3.33   4.98
2    60  123.66  132.33   74.85   7.34  20.14
3    90   84.47   98.81  166.19  13.14  42.10

What is going on here? What on earth is ``data['Time'] <= 90``? Let's print it to see:

In [51]:
data['Time'] <= 90

0     True
1     True
2     True
3     True
4    False
5    False
6    False
Name: Time, dtype: bool

It looks like a boolean ``Series`` object. It contains ``True`` and ``False`` values. When you pass it to the dataframe, it only keeps the rows where the condition is ``True``. This is neat!

What about getting the rows corresponding to times between 60 and 150 minutes? This is how you can do it:

In [75]:
data[(data['Time'] >= 60) & (data['Time'] <= 150)]

   Time     NO3     NO2      N2    NH3    N2O
2    60  123.66  132.33   74.85   7.34  20.14
3    90   84.47   98.81  166.19  13.14  42.10
4   120   30.24   38.74  249.78  19.54  55.98
5   150   27.94   10.42  292.32  24.07  60.65

Pay attention to the parentheses. They are necessary! The character ``&`` is the logical AND operator. It is applied element-wise to the ``Series`` objects. If it sees a ``True`` and a ``False``, it returns ``False``. Only if it sees two ``True``s, it returns ``True``. Note that this is different from the ``and`` operator in Python. If you try using ``and`` instead of ``&``, you will get an error.

Let's do an OR operation. For example, let's get the rows where the time is either less than 60 minutes or greater than 150 minutes:

In [76]:
data[(data['Time'] < 60) | (data['Time'] > 150)]

   Time     NO3     NO2      N2    NH3    N2O
0     0  500.00    0.00    0.00   0.00   0.00
1    30  250.95  107.32   18.51   3.33   4.98
6   180   13.54    6.11  309.50  27.26  62.54

The ``|`` operator is the logical OR operator. It is applied element-wise to the ``Series`` objects. If it sees a ``True`` or a ``False``, it returns ``True``. Only if it sees two ``False``s, it returns ``False``.

How do we do a NOT operation? The operator we need is ``~``. For example, let's get the rows where the time is not between 60 and 150 minutes:

In [77]:
data[~(data['Time'] >= 60) & (data['Time'] <= 150)]

   Time     NO3     NO2     N2   NH3   N2O
0     0  500.00    0.00   0.00  0.00  0.00
1    30  250.95  107.32  18.51  3.33  4.98

Let's repeat the total mass calculation that we did before:

In [78]:
total_mass = data.iloc[:, 1:].sum(axis=1)
total_mass

0    500.00
1    385.09
2    358.32
3    404.71
4    394.28
5    415.40
6    418.95
dtype: float64

The result of such manipulations is of type [Series](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html):

In [79]:
type(total_mass)

pandas.core.series.Series

Mass is not conserved in this reaction. This doesn't sound right. There should be another species that we are not taking into account. Let's call that species "X". The mass of that species is the total mass minus the mass of the other species:

In [80]:
mass_X = 500 - data.iloc[:, 1:].sum(axis=1)
mass_X

0      0.00
1    114.91
2    141.68
3     95.29
4    105.72
5     84.60
6     81.05
dtype: float64

Let's add a column to the dataframe:

In [91]:
data['X'] = mass_X
data

   Time     NO3     NO2      N2    NH3    N2O       X
0     0  500.00    0.00    0.00   0.00   0.00    0.00
1    30  250.95  107.32   18.51   3.33   4.98  114.91
2    60  123.66  132.33   74.85   7.34  20.14  141.68
3    90   84.47   98.81  166.19  13.14  42.10   95.29
4   120   30.24   38.74  249.78  19.54  55.98  105.72
5   150   27.94   10.42  292.32  24.07  60.65   84.60
6   180   13.54    6.11  309.50  27.26  62.54   81.05

Let's save our work to a new file:

In [98]:
data.to_csv('catalysis-with-X.csv', index=False)

Here are the contents of the new file:

In [99]:
!cat catalysis-with-X.csv

Time,NO3,NO2,N2,NH3,N2O,X
0,500.0,0.0,0.0,0.0,0.0,0.0
30,250.95,107.32,18.51,3.33,4.98,114.91000000000003
60,123.66,132.33,74.85,7.34,20.14,141.68
90,84.47,98.81,166.19,13.14,42.1,95.28999999999996
120,30.24,38.74,249.78,19.54,55.98,105.71999999999997
150,27.94,10.42,292.32,24.07,60.65,84.60000000000002
180,13.54,6.11,309.5,27.26,62.54,81.05000000000001

You can save the file in different formats. For example, you can save it in Excel format:

In [100]:
data.to_excel('catalysis-with-X.xlsx')

If you are working on Google Colab, download the file to your local machine. If you are working on your own computer, locate the file, and open it with Excel.

## Questions

Find all rows where NO3 concentration is greater than 100 g AND N2 concentration is less than 200 g. Display the first 5 rows. How many such data points exist?

In [103]:
newdata = pd.read_csv('catalysis-with-X.csv')
#print(newdata.columns)
print("First five rows: \n", newdata[:5])
print("There are three rows in the first five where this happens, at t=0,30,and 60")
print("\nRows where NO3>100g & N2<200g: \n", newdata[(newdata["NO3"]>100) & (newdata["N2"]<200)])

First five rows:
    Time     NO3     NO2      N2    NH3    N2O       X
0     0  500.00    0.00    0.00   0.00   0.00    0.00
1    30  250.95  107.32   18.51   3.33   4.98  114.91
2    60  123.66  132.33   74.85   7.34  20.14  141.68
3    90   84.47   98.81  166.19  13.14  42.10   95.29
4   120   30.24   38.74  249.78  19.54  55.98  105.72
There are three rows in the first five where this happens, at t=0,30,and 60

Rows where NO3>100g & N2<200g:
    Time     NO3     NO2     N2   NH3    N2O       X
0     0  500.00    0.00   0.00  0.00   0.00    0.00
1    30  250.95  107.32  18.51  3.33   4.98  114.91
2    60  123.66  132.33  74.85  7.34  20.14  141.68

Find all time points where EITHER (NO3 > 200 OR N2 > 250) AND NH3 < 20. Display only the Time, NO3, N2, and NH3 columns for these rows.

In [106]:
newdata[((newdata["NO3"]>100) | (newdata["N2"]>250)) & (newdata["NH3"]<20)][["Time","NO3","N2","NH3"]]

   Time     NO3     N2   NH3
0     0  500.00   0.00  0.00
1    30  250.95  18.51  3.33
2    60  123.66  74.85  7.34

Create two new columns in the DataFrame:
1. `total_products` - sum of all product concentrations (N2, NH3, N2O, X)
2. `conversion_ratio` - ratio of total_products to initial NO3 concentration (500g)

At which time point is the conversion ratio highest?

In [141]:
total_products = newdata.iloc[:, 3:7].sum(axis=1)
newdata["total_products"]=total_products
conversion_ratio = newdata["total_products"]/500
newdata["conversion_ratio"]=conversion_ratio
newdata

,Time,NO3,NO2,N2,NH3,N2O,X,total_products,conversion_ratio
0,0,500.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00000
1,30,250.95,107.32,18.51,3.33,4.98,114.91,141.73,0.28346
2,60,123.66,132.33,74.85,7.34,20.14,141.68,244.01,0.48802
3,90,84.47,98.81,166.19,13.14,42.10,95.29,316.72,0.63344
4,120,30.24,38.74,249.78,19.54,55.98,105.72,431.02,0.86204
5,150,27.94,10.42,292.32,24.07,60.65,84.60,461.64,0.92328
6,180,13.54,6.11,309.50,27.26,62.54,81.05,480.35,0.96070

In [124]:
print("The conversion ratio is the highest at t=180")

The conversion ratio is the highest at t=180

Create your own dataframe where the rows are the courses you are taking. The columns should be the course number, coursename, the instructor, and how much you're enjoying it on a scale of 1 to 5.

In [140]:
df=pd.DataFrame({"Course Number":["ECON 251","SCLA 101", "ME 164", "MA 266", "PHYS 172", "ENGR 10301POL", "EPCS 121", "ME 239"]
                 ,"Course Name":["Microeconomics", "Transformative Texts, Critical Thinking And Communication I: Antiquity To Modernity","Geometric And Annotation Modeling","Ordinary Differential Equations","Modern Mechanics","Introduction To Engineering In Practice", "First Year Participation In EPICS II", "Introduction To Data Science For Mechanical Engineers"]
                 ,"Instructor":["B Fan","M D Nichols", "E Kim", "A V Volkening","Y N Pushkar","S R Bailey","A G Samuel","R Maulik"]
                 ,"Enjoyment":[3,4,4,5,1,5,4,3]})

df

,Course Number,Course Name,Instructor,Enjoyment
0,ECON 251,Microeconomics,B Fan,3
1,SCLA 101,"Transformative Texts, Critical Thinking And Co...",M D Nichols,4
2,ME 164,Geometric And Annotation Modeling,E Kim,4
3,MA 266,Ordinary Differential Equations,A V Volkening,5
4,PHYS 172,Modern Mechanics,Y N Pushkar,1
5,ENGR 10301POL,Introduction To Engineering In Practice,S R Bailey,5
6,EPCS 121,First Year Participation In EPICS II,A G Samuel,4
7,ME 239,Introduction To Data Science For Mechanical En...,R Maulik,3